### ISSUE TITLE
SEA installed from .deb file don't work on Linux

### ISSUE THREAD

**Issue by jmz-bit** [ball-network/seacoin-blockchain#6]
SEA installed from .deb file (CLI and GUI versions) don't work on Linux.

Impossible to connect to any peers.

2024-02-15T15:41:15.597 wallet wallet_server              : ERROR    Exception [Errno 104] Connection reset by peer, exception Stack: Traceback (most recent call last):
  File "sea/server/server.py", line 436, in start_client
  File "aiohttp/client.py", line 825, in _ws_connect
  File "aiohttp/client.py", line 601, in _request
  File "aiohttp/client_reqrep.py", line 965, in start
  File "aiohttp/streams.py", line 622, in read
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer

2024-02-15T15:44:29.306 full_node full_node_server        : ERROR    Exception [Errno 104] Connection reset by peer, exception Stack: Traceback (most recent call last):
  File "sea/server/server.py", line 436, in start_client
  File "aiohttp/client.py", line 825, in _ws_connect
  File "aiohttp/client.py", line 601, in _request
  File "aiohttp/client_reqrep.py", line 965, in start
  File "aiohttp/streams.py", line 622, in read
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer

Linux version installed from source works OK.

Windows version installed from .exe is working OK.

**Comment by ball-network** [comment]
Please update your program to the latest version
